export const GET_ALL_DOCTORS_REQUEST = 'GET_ALL_DOCTORS_REQUEST';
export const GET_ALL_DOCTORS_SUCCESS = 'GET_ALL_DOCTORS_SUCCESS';
export const GET_ALL_DOCTORS_FAILURE = 'GET_ALL_DOCTORS_FAILURE';

export const GET_DOCTOR_REQUEST = 'GET_DOCTOR_REQUEST';
export const GET_DOCTOR_SUCCESS = 'GET_DOCTOR_SUCCESS';
export const GET_DOCTOR_FAILURE = 'GET_DOCTOR_FAILURE';

export const DELETE_DOCTOR_REQUEST = 'DELETE_DOCTOR_REQUEST';
export const DELETE_DOCTOR_SUCCESS = 'DELETE_DOCTOR_SUCCESS';
export const DELETE_DOCTOR_FAILURE = 'DELETE_DOCTOR_FAILURE';

export const UPDATE_DOCTOR_REQUEST = 'UPDATE_DOCTOR_REQUEST';
export const UPDATE_DOCTOR_SUCCESS = 'UPDATE_DOCTOR_SUCCESS';
export const UPDATE_DOCTOR_FAILURE = 'UPDATE_DOCTOR_FAILURE';

export const GET_DOCTOR_BY_CLINIC_ID_REQUEST = 'GET_DOCTOR_BY_CLINIC_ID_REQUEST';
export const GET_DOCTOR_BY_CLINIC_ID_SUCCESS = 'GET_DOCTOR_BY_CLINIC_ID_SUCCESS';
export const GET_DOCTOR_BY_CLINIC_ID_FAILURE = 'GET_DOCTOR_BY_CLINIC_ID_FAILURE';
