export const SEARCH_CLINICS_REQUEST = 'SEARCH_CLINICS_REQUEST';
export const SEARCH_CLINICS_SUCCESS = 'SEARCH_CLINICS_SUCCESS';
export const SEARCH_CLINICS_FAILURE = 'SEARCH_CLINICS_FAILURE';

export const SEARCH_DOCTORS_REQUEST = 'SEARCH_DOCTORS_REQUEST';
export const SEARCH_DOCTORS_SUCCESS = 'SEARCH_DOCTORS_SUCCESS';
export const SEARCH_DOCTORS_FAILURE = 'SEARCH_DOCTORS_FAILURE';
