export const ADD_SLOTS_REQUEST = 'ADD_SLOTS_REQUEST';
export const ADD_SLOTS_SUCCESS = 'ADD_SLOTS_SUCCESS';
export const ADD_SLOTS_FAILURE = 'ADD_SLOTS_FAILURE';

export const AVAILABLE_SLOTS_REQUEST = 'AVAILABLE_SLOTS_REQUEST';
export const AVAILABLE_SLOTS_SUCCESS = 'AVAILABLE_SLOTS_SUCCESS';
export const AVAILABLE_SLOTS_FAILURE = 'AVAILABLE_SLOTS_FAILURE';

export const FILTER_SLOTS_REQUEST = 'FILTER_SLOTS_REQUEST';
export const FILTER_SLOTS_SUCCESS = 'FILTER_SLOTS_SUCCESS';
export const FILTER_SLOTS_FAILURE = 'FILTER_SLOTS_FAILURE';

export const SCHEDULE_APPOINTMENT_REQUEST = 'SCHEDULE_APPOINTMENT_REQUEST';
export const SCHEDULE_APPOINTMENT_SUCCESS = 'SCHEDULE_APPOINTMENT_SUCCESS';
export const SCHEDULE_APPOINTMENT_FAILURE = 'SCHEDULE_APPOINTMENT_FAILURE';

export const GET_APPOINTMENT_REQUEST = 'GET_APPOINTMENT_REQUEST';
export const GET_APPOINTMENT_SUCCESS = 'GET_APPOINTMENT_SUCCESS';
export const GET_APPOINTMENT_FAILURE = 'GET_APPOINTMENT_FAILURE';

export const UPDATE_APPOINTMENT_REQUEST = 'UPDATE_APPOINTMENT_REQUEST';
export const UPDATE_APPOINTMENT_SUCCESS = 'UPDATE_APPOINTMENT_SUCCESS';
export const UPDATE_APPOINTMENT_FAILURE = 'UPDATE_APPOINTMENT_FAILURE';
